### ISSUE TITLE
The .bat file references wrong versions of jar files

### ISSUE THREAD

**Issue by poi519** [pojosontheweb/rjar#4]
I have downloaded a zip archive for version 0.6
Bat file didn't work because it referenced old versions of jars for groovy and rjar itself, please consider making .bat file version independent

**Comment by vankeisb** [comment]
You are right, I changed the deps and versions but forgot the scripts. Fixing this right now. I have little time for doing something more clever, plus I don't ship new versions often, so I'll only patch for now. But yes, this would be way better to do this automatically, based on the version in the pom (ant/maven filtering ?)
Thanks for the feedback !

**Comment by vankeisb** [comment]
Fixed in r0.6.1.
